### ISSUE TITLE
Unmanaged signal ctrl+z

### ISSUE THREAD

**Issue by ihwang** [ihwang/42sh#11]
#### Test
```
$> mkfifo fifo
$> ls -lR /usr >fifo 2>&1 &
$> fg %[the job number]
^Z
```
Doesn't suspend `ls-lR`

**Comment by xopxop** [comment]
Fixed, in function lauch_in_child_process
move sig_controller(CHILD) to the top the catch the signal

**Comment by xopxop** [comment]
Need to redesign the position of each signal in lauching child process

**Comment by xopxop** [comment]
Fixed: by adding SIGTSTP
