### ISSUE TITLE
Irrational test cases for job control in eval form

### ISSUE THREAD

**Issue by ihwang** [ihwang/42sh#12]
```
$> mkfifo fifo
$> ls -lR /usr >fifo 2>&1 &
$> jobs
{{ Message indicating that the "ls" command is being executed }}
$>
```

```
$> emacs -nw &
$> emacs -nw &
$> emacs -nw &
$> emacs -nw &
$> emacs -nw &
$> jobs
{{ Message indicating that 5 instances of emacs are stopped in the background }}
$>
```
```
$> fg %{{ one of the emacs job number }}
```
```
$> jobs
{{ The "ls" command launched above must be the only one left }}
$> cat -e {{ Output of the "ls" command. Do not wait until the end, cut the display with CTRL-C }}
$> jobs
$>
```
```
$> ls -Rl / 2>&1
{{ Display of the "ls" command. Don't wait until the end, press CTRL-Z }}
{{ Message indicating that the order is suspended }}
$> jobs
{{ Message indicating that the order is suspended }}
$>
```
```
$> ps a | grep "ls -Rl /" | grep -v 'grep' | cut -d ' ' -f 2
{{ PID of the command "ls" from the previous test }}
$> kill {{ PID of the command "ls" from the previous test }}
$> jobs
{{ Message indicating that the order has ended }}
$>
```
```
$> jobs
$> ps a | grep "ls -Rl /" | grep -v 'grep'
$>
```

**Comment by xopxop** [comment]
Evaluation form for this part is trash:
"cat -e" command should be replaced by "fg" command
It should be execute in this order in our shell or in normal shell like this:

$> mkfifo fifo
$> ls -lR /usr >fifo 2>&1 &
$> jobs
{{ Message indicating that the "ls" command is being executed }}
$>
---
$> emacs -nw &
$> emacs -nw &
$> emacs -nw &
$> emacs -nw &
$> emacs -nw &
$> jobs
{{ Message indicating that 5 instances of emacs are stopped in the background }}
$>
--
$> fg %{{ one of the emacs job number }}
--
$> jobs
{{ The "ls" command launched above must be the only one left }}
$> fg {{ Output of the "ls" command. Do not wait until the end, cut the display with CTRL-C }}
$> jobs
$>
--
$> ls -Rl / 2>&1
{{ Display of the "ls" command. Don't wait until the end, press CTRL-Z }}
{{ Message indicating that the order is suspended }}
$> jobs
{{ Message indicating that the order is suspended }}
$>
--
$> ps a | grep "ls -Rl /" | grep -v 'grep' | cut -d ' ' -f 2
{{ PID of the command "ls" from the previous test }}
$> kill {{ PID of the command "ls" from the previous test }}
$> jobs
{{ Message indicating that the order has ended }}
$>
--
$> jobs
$> ps a | grep "ls -Rl /" | grep -v 'grep'
$>
