### ISSUE TITLE
pasting problem

### ISSUE THREAD

**Issue by VictoriaElisabet** [ihwang/42sh#121]
smth has happened to the line edition now
PATH=f echo test
malloc(): invalid size (unsorted)
Aborted
i get this when I first paste in PATH=/bin:/usr/bin
deletes /bin:/usr/bin
and replaces it with f
and the writes echo test
and runs it
I get aborted...
basically if you paste smth, deletes some part of it and runs it it gives error

**Comment by robkle** [comment]
It happens when you copy and paste from outside 42sh and then delete delete something. E.g. if you copy paste 'echo hello world' and delete world, once you press enter, it will abort.

**Comment by ihwang** [comment]
@VictoriaElisabet @robkle Thanks for reporting I will fix that by today.
