### ISSUE TITLE
Line edition after using history search which related to quotation

### ISSUE THREAD

**Issue by xopxop** [ihwang/42sh#16]
The bug happens when:
$> abc "
dquote> "
After that using uper key to go back to the command and it should be like this
$> echo "abc
"
The bug happens when you start delete the line, and it will start printing gibberish

**Comment by xopxop** [comment]
I can give a couple of approach to solve this problem, since I think It shouldnt be difficult to solve
Eg. taking the previous example, the line in line.edition struct will be like this: abc "\n"
So, when the line edition read the line when moving throw the line and when it hit the \n we definitely have to go up one line and calculate the cursor position in the line above.
Since when editing the line, there will be no ways we can add \n line feed into a string and it only happens when the string is already made (in the example the string come from the history part). Therefore we can add one more rule for the line edition logic

**Comment by ihwang** [comment]
@xopxop Definitely. It may need one more rule to check the saved history whether it has '\n' character in it or not.

**Comment by robkle** [comment]
Intaek and I discussed this today, and I've made a start with it. Might take a day or two still.

**Comment by robkle** [comment]
I created termcap branch for fixing this. The functions that are related with counting rows, and calculating the position of the index and cursor, are in a new file called row_count.c (under src/cores/line_edition). The issue with line edition info from history should be completely fixed before fixing this issue.

**Comment by xopxop** [comment]
issue #23, duplication

**Comment by robkle** [comment]
Line edition handles multi-line commands with \n. Needs to be tested. Changes are on the termcap branch.

**Comment by robkle** [comment]
This issue has a new bug, which came up during Dudu's tests: History management does not recognize ctrl-D when it reads from .history file to history array. This creates problems when a command has an opening quote followed by ctrl-D (i.e. no closing quote). I will work fix that.

**Comment by robkle** [comment]
Reading from .history file seems to work now. Let's keep this issue open until we merge termcap branch to master branch.

**Comment by robkle** [comment]
Line edition and history issues fixed and merged to master branch.
