### ISSUE TITLE
Commands containing pipe emit signals randomly

### ISSUE THREAD

**Issue by ihwang** [ihwang/42sh#18]
#### Cases
1. SIGTTOU
```
42sh tango [~/42/42sh][0]
> ls | grep 42sh

42sh tango [~/42/42sh][150]
>
```

2. SIGPIPE
``` 
42sh tango [~/42/42sh][150]
> ls | exit
SIGPIPE sent: 13
42sh tango [~/42/42sh][141]
>
```

As I tested, random emitting of signals happen only with which creates child process like ls.
For example, `echo HI | grep HI` didn't emit such signals.

**Comment by xopxop** [comment]
This probably a bug coming from when I was refactoring, I will have a look at it

**Comment by ihwang** [comment]
FYI, the line `SIGPIPE sent: 13` in the second case has been added since this commit `103a2f1e360be844a01e38530293697b55e837b4`
