### ISSUE TITLE
Incorrect information printing after executing non existing command within piped command

### ISSUE THREAD

**Issue by ihwang** [ihwang/42sh#19]
### Case
```
42sh tango [~/42/42sh][1]
> ls | noexistingcommand
42sh tango 42sh: noexistingcommand: command not found
[~/42/42sh][150]
>
```
This error could happen occasionally but quite often, so if you don't see the error at once, please try more.

P.S. It seems to be related to #18 as well especially with SIGTTOU

**Comment by xopxop** [comment]
This error which over printing the promp only happens on Linux I think
