### ISSUE TITLE
memory issues with pasting 

### ISSUE THREAD

**Issue by VictoriaElisabet** [ihwang/42sh#21]
If one copies a text and start pasting it by rightclicking and then decides to scroll up and in the history to come back to the first command again and start pasting even more it will give this error and close the shell.

> copyopyopyopyopyopyopyopyopyopyopyopyopyopyopyopyopyopyopyopyopyopy   opyopyopyopyopyopyopyopyopyopy opyopyopyopyopymalloc(): corrupted top size
Aborted

> faffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafafffafaf42sh: malloc.c:2385: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted

**Comment by ihwang** [comment]
@VictoriaElisabet Could you please try the same actions in the `termcap` branch? I made a change, and it seems gone, but think it's better to double-check with you.

**Comment by VictoriaElisabet** [comment]
I tried this now and and it seems like the memory leak problem is gone but now if you start writing a command and decides to go back into the history to return to what you were writing it can no longer be found.

E.g. 
>gdgisgjdsgogidjg

scroll upp in the history and come back

this can no longer be found, instead you need to type in everything again. Is that correct behaviour?
>gdgisgjdsgogidjg

**Comment by robkle** [comment]
if (tmp != NULL)
    ft_strdel(&tmp);
in the up_down function fixed the memory leak, but created the issue that Victoria is talking about. tmp holds the command typed in before navigating up and down through history. By deleting tmp, that command is lost. We need to think of another way to fix the leak (or to handle the typed in command).

**Comment by ihwang** [comment]
@robkle Thanks for reporting. I should've been more careful with that. Will think about solutions for that.
