### ISSUE TITLE
Bug with piping 

### ISSUE THREAD

**Issue by VictoriaElisabet** [ihwang/42sh#22]
ls | sort -rn | cat -e

this command leaves hanging

**Comment by VictoriaElisabet** [comment]
base64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/g

this one too, atleast it doesn't print the prompt again

**Comment by ihwang** [comment]
This seems to be duplicated to #19
