### ISSUE TITLE
Enhance built-in functions

### ISSUE THREAD

**Issue by xopxop** [ihwang/42sh#26]
Hei team, we need to enhance our built-in functions by checking if the stdout is closed or not, if it is close then we need to add this line
if (fcntl(STDOUT_FILENO, F_GETFD) == -1)
{
	ft_dprintf(2, "%s: %s: Write error: Bad file descriptor\n", SHELL_NAME, your_built-in_name);
	return (1);
}
eg: in the ft_echo

int			ft_echo(t_process *p)
{
	int		i;
	int		is_opt_n;
	int		is_stop;

	if (fcntl(STDOUT_FILENO, F_GETFD) == -1)
	{
		ft_dprintf(2, "%s: echo: Write error: Bad file descriptor\n", SHELL_NAME);
		return (1);
	}
	i = 0;
	is_opt_n = FALSE;
	is_stop = FALSE;
	while (is_stop == FALSE && ++i < p->ac && \
		p->av[i][0] == '-' && ft_strlen(p->av[i]) > 1)
		is_stop = apply_option(p->av[i], &is_opt_n);
	while (i < p->ac)
	{
		ft_putstr(p->av[i]);
		if (i + 1 != p->ac && ft_strcmp(p->av[i], ""))
			ft_putstr(" ");
		i++;
	}
	if (is_opt_n == FALSE)
		ft_putchar('\n');
	return (EXIT_SUCCESS);
}

NOTE: if there is function which needs the input from stdin then it is safe to do the same thing with stdin

**Comment by xopxop** [comment]
example command:
echo abc >&-
type ... >&-
Check the same command in bash for more info

**Comment by VictoriaElisabet** [comment]
Added for alias, unalias and hash

**Comment by xopxop** [comment]
added for env, set, and i think it is enough, since macos dont even handle it in alias, set,env ...
