### ISSUE TITLE
Shell error code doesn't change occasionally

### ISSUE THREAD

**Issue by ihwang** [ihwang/42sh#3]
#### Test
```
42sh  [/42/42sh][1]
> cat author
ihwang
dthan
rklein
Vgrankul
42sh  [/42/42sh][0]
> echo hi
hi
42sh  [/42/42sh][0]
> asdf
42sh: asdf: command not found
42sh  [/42/42sh][127]
> echo hi
hi
42sh  [/42/42sh][127]
>
```

**Comment by xopxop** [comment]
I think, most of the wrong exit code will come from built-in command from parent shell.
So basically for what happens is you need come up with a solution for p->status type
right now i define the type of status in the execution.h (line 17-23)
process status:
NOT_COMPLETED = 0 (this cause the issue why exit status of built in command is not changed) -> maybe change it into -1
COMPLETED = 1
NOT_STOPPED = 0 (Dont touch)
STOPPED 1 (Dont touch)
UNAVAILABLE_STATUS 0 (not sure about this)
COMPLETED_JOB = 1 (Dont touch)
SUSPENDED_JOB = 2 (Dont touch)
There are some define which you dont need to care about, i comment next to it, but it is always safe to check, i will come back and check those later too, if it may break sth
So, the next thing to look at is the file src/corse/executor/lauch_process/lauch_process.c in function launch_simple_command which will return if the process is completed or not. What i did wrong here is i made p->status (NOT_COMPLETED == 0) which need to changed
and in the line 72 	return ((p->status == NOT_COMPLETED) ? g_shell.exit_status : p->status);
maybe is should be changed sth like this:
return ((p->status == -1) ? g_shell.exit_status : p->status);

**Comment by robkle** [comment]
Dudu's idea to change NOT_COMPLETED to -1 fixed this issue.

**Comment by xopxop** [comment]
Need to check the NOT_COMPLETE value
