### ISSUE TITLE
type builtin

### ISSUE THREAD

**Issue by VictoriaElisabet** [ihwang/42sh#30]
type ls gggg ls

prints 

ls is /usr/bin/ls
bash: type: gggg: not found
ls is /usr/bin/ls

return type = 0

bash gives return type 1 for the same command, which is correct?

**Comment by xopxop** [comment]
mine return 127 when command not found

**Comment by VictoriaElisabet** [comment]
so you get return 127 when you run this command?
type ls gggg ls

**Comment by xopxop** [comment]
basically, it should return sth different than 0. Normally, if the command not found
eg: 
$> doesnotexists
will return 127, so i guess 127 make more senses however, it is up to the one who fixes it, just return sth different than 0 then i think it is fine

**Comment by VictoriaElisabet** [comment]
aaah, yes like that, then it should return smth else than 0 but in this case its about that the command ggg can't be found in the type builtin

**Comment by ihwang** [comment]
@VictoriaElisabet @xopxop Thanks for reporting.
I also tested the command in two machines, 
In GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20), the command returns 0.
In GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu), the command returns 1.
So I guess It depends on bash version.
And also, I would like to ask you guys which implementation I should follow.

**Comment by VictoriaElisabet** [comment]
I think as long as the approach you choose is defendable it doesnt matter which one you choose!

**Comment by xopxop** [comment]
Yes, u can choose what approach u want to as long as u can bring a good reason, and that reason it is good enough for me. Btw, remember to close the issue, after u fix some thing ;)
