### ISSUE TITLE
Window resizing is not recognised during line edit

### ISSUE THREAD

**Issue by robkle** [ihwang/42sh#33]
- Type a simple command that contains more characters than columns in the window
- Navigate through the command (left, right, home, end, etc.). All goes well.
- Resize the window, and navigate through the command again. Cursor motion is still bound by previous window size.

This bug is on the master branch, so it is not introduced by my recent line-edit changes.
There has to be something in the ft_read_input function (in src/cores/line_edition/ft_get_line.c) that updates the co variable in the line_edition struct, either everytime a key is pressed, or whenever the window size changes.

**Comment by ihwang** [comment]
@robkle Thanks for reporting. I made a room for updating that info such as co, starting_row and total_row in termcap branch.
And I think this issue is also related to #16 as there will be similar cases like earlier line feed characters or dquote phase, etc.
