### ISSUE TITLE
Leak when running commands

### ISSUE THREAD

**Issue by VictoriaElisabet** [ihwang/42sh#34]
If one is creating an alias.
E.g. alias test=ok
and then runs test
> test

it causes memory leaks

==3956== 28 (24 direct, 4 indirect) bytes in 1 blocks are definitely lost in loss record 37 of 66
==3956==    at 0x483577F: malloc (vg_replace_malloc.c:299)
==3956==    by 0x403E8D: non_operator_token (non_operator_token.c:35)
==3956==    by 0x403FDD: select_non_operator_token (non_operator_token.c:55)
==3956==    by 0x4041D3: get_non_operator_token (non_operator_token.c:81)
==3956==    by 0x40473E: token_creator_service (token_creator.c:27)
==3956==    by 0x4031FE: lexical_analysis_service (lexical_analysis.c:53)
==3956==    by 0x402E76: lexical_and_syntax_analysis (tokenizing_service.c:33)
==3956==    by 0x402DFA: tokenizing_service_helper (tokenizing_service.c:56)
==3956==    by 0x402F85: tokenizing_service (tokenizing_service.c:79)
==3956==    by 0x4014F3: shell (main.c:43)
==3956==    by 0x401422: main (main.c:78)

**Comment by xopxop** [comment]
I will check it
