### ISSUE TITLE
Double free with auto completion (Not happens in master branch anymore, but could Intaek have a look)

### ISSUE THREAD

**Issue by xopxop** [ihwang/42sh#37]
This autocompletion seems only happens when auto-complete a hidden file. Eg
$> echo .history

**Comment by xopxop** [comment]
Updated: I checked it in the master branch and the double free is no longer happens. However, when i do work with Robert and in the term_cap branch, the double free always happens when we tried to auto-complete a hidden file. Could you have a look on this, Intake? Did u already fix it in the master branch? :D

**Comment by ihwang** [comment]
@xopxop Will have a look!
