### ISSUE TITLE
Shell enhancement: Add Built-in function in both parent-shell and child shell (alias, etc...)

### ISSUE THREAD

**Issue by xopxop** [ihwang/42sh#38]
Check and Add your built-ins in these 2 files:
lauch_process_parent_shell.c
execute_in_child_process.c

**Comment by xopxop** [comment]
example #35

**Comment by ihwang** [comment]
Added `ft_export()` in `is_builtin()` and `exec_builtin2()` into execute_in_child_process.c file.
Seems nothing to do more with this issue.

**Comment by xopxop** [comment]
- In execute_in_child_process.c:
Add your built-in fucntion in function exec_builtin2() and is_builtin()
- In lauch_process_parent_shell.c
Add in function lauch_process_which_can_change_shell2()
and in lauch_process.c
Add is_execute_on_parent_process()

**Comment by VictoriaElisabet** [comment]
Apparantely closed this when I pushed my changes, I will reopen it since I dont know if everyone has added their builtins.
Alias, unalias and hash is now added

**Comment by ihwang** [comment]
I've added every builtin function needed by the shell.

**Comment by xopxop** [comment]
it is now complete, i will close this one
