### ISSUE TITLE
A leak in termcap branch since this commit

### ISSUE THREAD

**Issue by ihwang** [ihwang/42sh#39]
#### How to reproduce
```
42sh tango [~/42/42sh_termcap][1]
> d
42sh: d: command not found
42sh tango [~/42/42sh_termcap][127]
> d
42sh: d: command not found
42sh tango [~/42/42sh_termcap][127]
> d
42sh: d: command not found
```
The leak appeared for the first time from this commit in termcap branch.
2abedffce5a54c5f1717adbd1c2550571ba57403
And lasting upto the latest master.
260d706edbd7aa08ee482e67720e547e22602f70

**Comment by xopxop** [comment]
close it since we new focus on the master

**Comment by ihwang** [comment]
@xopxop Could you please test it with Valgrind? As I see, It hasn't been fixed in master branch yet.

**Comment by xopxop** [comment]
yes, it is in the history, as i investigated, I need Robert in this one, so i open the #42

**Comment by ihwang** [comment]
Okay.
