### ISSUE TITLE
Execution of non-permitted command doesn't print error message

### ISSUE THREAD

**Issue by ihwang** [ihwang/42sh#43]
### How to reproduce
on linux,
```
42sh  [/42/42sh][1]
> chmod -x /usr/sbin/sysctl
42sh  [/42/42sh][0]
> sysctl
42sh  [/42/42sh][1]
>
```
Don't forget to give back the permission after testing :)

on OSX,
```
42sh tango [~/42/42sh][1]
> cupsd
42sh tango [~/42/42sh][1]
> 
```

**Comment by xopxop** [comment]
can u elaborate this issue? so we can assign a correct person to fix this issue

**Comment by ihwang** [comment]
@xopxop Sure, so the point is that, when running a command which doesn't have permission to execute, an error message has to be printed. But our shell doesn't do so. What I mean by the permission to execute is what you can see with `ls -l` command.

**Comment by xopxop** [comment]
I think @ihwang  or @VictoriaElisabet  could know sth about this the best. Since it is about the executing a process, @ihwang is the first one who wrote the code then @VictoriaElisabet  has done hash table on top of it. Maybe you 2 can have a look at this together

**Comment by ihwang** [comment]
@xopxop  Will have a look at the specific.

**Comment by VictoriaElisabet** [comment]
@xopxop should I look at this issue?

**Comment by xopxop** [comment]
tbh, i dont know how to reproduct this one

**Comment by xopxop** [comment]
ahhh

**Comment by xopxop** [comment]
No, i still not get it XD

**Comment by xopxop** [comment]
lol, just forget my comments above XD

**Comment by VictoriaElisabet** [comment]
What ? XD tell me if I need to check smth

**Comment by xopxop** [comment]
it is about the permission to execute a binary file or a command like this
$> touch a.out                -----> create a binary file
$> chmod -x a.out          ------> turn off all the execution permission, author, group, and anyone
$> ./a.out                        ------> you will see the output

**Comment by VictoriaElisabet** [comment]
but what is the bug here? running ./a.out prints permission denied

**Comment by ihwang** [comment]
@VictoriaElisabet My explanation wasn't enough. When you execute some commands which you can find in PATH env, are not permitted to execute, the shell has to print out an error message. I started working on it, and it seems a small thing so I think I can manage this alone.
