### ISSUE TITLE
Redirecting from FD 3 and 4 to a file causes new bug

### ISSUE THREAD

**Issue by ihwang** [ihwang/42sh#44]
Redirecting from file descriptor 3 and 4 always causes the problem.
It's ok with file descriptors bigger than 4.

#### How to reproduce
1. `echo abc 3>random_file_name`
2. `echo abc 4>random_file_name`

The error messages what Valgrind emits vary depending on which file descriptor you use.

**Comment by xopxop** [comment]
I will fix it soon

**Comment by xopxop** [comment]
Fixed by adding one rule in the redirection great only
