### ISSUE TITLE
Ctrl+right arrow key produces a memory issue

### ISSUE THREAD

**Issue by ihwang** [ihwang/42sh#45]
#### How to reproduce
1. Copy and paste this command from outside of the shell (Including `$>`)
`$> base64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/g`
2. Move the cursor left with ctrl+left until it hits the first position in the command.
3. Move the cursor right with ctrl+right one time.

Not a direct segfault, but possibly could happen during the evaluation.
Tested with Valgrind.

**Comment by ihwang** [comment]
I'll have a look at this first.

**Comment by robkle** [comment]
I know where the problem is. It is not a leak, but an invalid read because of l->line[index - 1] in the if and while statements.

**Comment by robkle** [comment]
Fixed. I will close this issue when I merge to the master branch.

**Comment by robkle** [comment]
Fixed

**Comment by ihwang** [comment]
Thanks!
