### ISSUE TITLE
In history part, !<any_command> prints extra lines

### ISSUE THREAD

**Issue by ihwang** [ihwang/42sh#47]
#### How to reproduce
```
42sh  [/42/42sh][0]
> echo abc
abc
42sh  [/42/42sh][0]
> !echo
echo abc

abc
42sh  [/42/42sh][0]
> !echo
echo abc


abc
42sh  [/42/42sh][0]
>
```
So, here we can get that the number of extra lines is being accumulated by trying the same command multiple times.

**Comment by robkle** [comment]
Fixed. I will close this issue once I merge to the master branch.

**Comment by robkle** [comment]
Fixed
