### ISSUE TITLE
Commands containing a logical operator works in the opposite way

### ISSUE THREAD

**Issue by ihwang** [ihwang/42sh#5]
#### Test
Below should have printed an error message 'Bad file descriptor' but haven't.
Additionally, 'out2' shouldn't have been printed with the '&&' operator.
```
42sh  [/42/42sh][258]
> echo out >&- && echo out2
out2
```

The opposite way
```
42sh  [/42/42sh][258]
> echo out >&- || echo out2
42sh  [/42/42sh][258]
>
```

**Comment by xopxop** [comment]
this bug should relates to the echo since, in here we close the stdin file descriptor, there for when echo check for the file descriptor, it wont be about to find it or write into, but there is no error here

**Comment by ihwang** [comment]
I guess this issue requires further discussion since the 'echo' should have been blocked before being executed by shell.

**Comment by xopxop** [comment]
Closed issue and open a new one for the team
