### ISSUE TITLE
Different exit output

### ISSUE THREAD

**Issue by xopxop** [ihwang/42sh#51]
Bash exit
----------------------------------------------
Vans-MacBook-Pro:~ dthan$ sh
sh-3.2$ exit 999999999999999999999999999999999999999999
exit
sh: exit: 999999999999999999999999999999999999999999: numeric argument required
Vans-MacBook-Pro:~ dthan$ echo $?
255

Our exit
-----------------------------------------------
42sh dthan [~/Desktop/42sh][1]
> exit 999999999999999999999999999999999999999999
Vans-MacBook-Pro:42sh dthan$ echo $?
255
Vans-MacBook-Pro:42sh dthan$

**Comment by ihwang** [comment]
Thanks for reporting. The number limit `exit` can handle is long long int which is 9223372036854775807.
So, 9223372036854775807 + 1 will say the error message.
Will add a rule to exit.
