### ISSUE TITLE
Autocompletion with .. is incorect

### ISSUE THREAD

**Issue by xopxop** [ihwang/42sh#74]
There are 2 things i found during testing the #70 
1. cd ..   ---> tab -- > the out put is "cd ../../" which is wrong
2. cd .. and press a long tab, it will print rubbish or mess up the line_edition

**Comment by ihwang** [comment]
@xopxop I fixed them cd and auto_completion in different branches. So I think such bugs have been fixed in auto_completion branch. Could you try the same in the branch, please?

**Comment by xopxop** [comment]
@ihwang it is the same branch as #70

**Comment by xopxop** [comment]
basically, u dont have to use cd, just any command with autocompletion

**Comment by xopxop** [comment]
@ihwang , yes it happens on your auto_completion branch

**Comment by VictoriaElisabet** [comment]
Cannot reproduce this problem..

**Comment by xopxop** [comment]
Sr, i made u confused. I will close it one, and move it to the #70 with all the bugs i found, since it happens only on the ihwang/auto_completion branch
