### ISSUE TITLE
cd /bin

### ISSUE THREAD

**Issue by VictoriaElisabet** [ihwang/42sh#77]
run: cd /bin
run pwd
for some reason pwd prints out /usr/bin and not /bin.

why?

**Comment by ihwang** [comment]
@VictoriaElisabet  It's because /bin is a symbolic link of /usr/bin
```
/
total 72
drwxr-xr-x  13 root root    4096 Mar 25 18:42 42
lrwxrwxrwx   1 root root       7 Apr 23  2020 bin -> usr/bin
drwxr-xr-x   2 root root    4096 Apr 15  2020 boot
drwxr-xr-x   5 root root     380 Mar 21 02:32 dev
```
This is my root directory. And you can see bin is a symbolic link of /usr/bin.
I guess your directory is the same with mine.

**Comment by ihwang** [comment]
Need to check that again. Thanks for reporting.

**Comment by ihwang** [comment]
@VictoriaElisabet 
In short, because it depends on the implementation of `pwd` and I think it is defendable during the eval.

And I think It would be better to call or text me if you need more info about this :)

**Comment by VictoriaElisabet** [comment]
That explanations is enough, I will close the issue
