### ISSUE TITLE
single quotes shouldn't be excapable

### ISSUE THREAD

**Issue by VictoriaElisabet** [ihwang/42sh#83]
Issues:

Add internal variable a='"'
seems to write out rubbish and also incorrectly when expanding 
it should print only "

42sh Tommi [~/ROOTCODE/42sh_ihwang][1]
> a='"'
42sh Tommi [~/ROOTCODE/42sh_ihwang][0]
> echo "${a}"
'"B
42sh Tommi [~/ROOTCODE/42sh_ihwang][0]
> echo "${a}"
'"0
42sh Tommi [~/ROOTCODE/42sh_ihwang][0]
> echo "${a}"
'"
42sh Tommi [~/ROOTCODE/42sh_ihwang][0]
> echo "${a}"
'"0
42sh Tommi [~/ROOTCODE/42sh_ihwang][0]
> echo "${a}"
'"0
42sh Tommi [~/ROOTCODE/42sh_ihwang][0]
> echo "${a}"
'"
42sh Tommi [~/ROOTCODE/42sh_ihwang][0]
> echo "${a}"
'"

same problem with a='""""""""'
should print """"""""

42sh Tommi [~/ROOTCODE/42sh_ihwang][127]
> a='"""""""""""""""""""""""""""""""""""""""""""""""'
42sh Tommi [~/ROOTCODE/42sh_ihwang][127]
> "${a}"
42sh: '"Mono.framewo: command not found

Another problem:

Bash:
Tommi-2:42sh_ihwang Tommi$ a=\\
Tommi-2:42sh_ihwang Tommi$ set | grep a=
a='\'

Our 42sh
42sh Tommi [~/ROOTCODE/42sh_ihwang][1]
> a=\\
42sh Tommi [~/ROOTCODE/42sh_ihwang][0]
> set | grep a=
a=\\
42sh Tommi [~/ROOTCODE/42sh_ihwang][0]
>

Also this:

Bash
Tommi-2:42sh_ihwang Tommi$ echo '\'
\

Our shell
42sh Tommi [~/ROOTCODE/42sh_ihwang][1]
> echo '\'
42sh: unexpected EOF while looking for matching `''
42sh: syntax error: unexpected end of file
42sh Tommi [~/ROOTCODE/42sh_ihwang][258]
>

**Comment by VictoriaElisabet** [comment]
Also this one

42sh Tommi [~/ROOTCODE/42sh_ihwang][0]
> a=\
42sh Tommi [~/ROOTCODE/42sh_ihwang][0]
> echo '${a}'
\
42sh Tommi [~/ROOTCODE/42sh_ihwang][0]
>

**Comment by VictoriaElisabet** [comment]
Note! singlequotes shouldn't be escapeable

**Comment by xopxop** [comment]
[MR link](https://github.com/ihwang/42sh/pull/95)
