### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by VictoriaElisabet** [ihwang/42sh#99]
42sh
>  echo $((65536 * 256 / 1024 % 2147483648)
cmdsubst> )
42sh: syntax error in expression

Bash
echo $((65536 * 256 / 1024 % 2147483648)
> )
bash: 65536: command not found

Is that ok?

**Comment by xopxop** [comment]
kinda, however, in your test it now became command substitution

**Comment by VictoriaElisabet** [comment]
I'll close it!
